### ISSUE TITLE
Project consultations sign-up

### ISSUE THREAD

**Issue by rickecon** [rickecon/StructEst_W19#3]
Dear MACS 40200 Structural Estimation students,

I have created a `Projects` directory in this repository with a `README.md` that has some nice resources for you. The first resource is a sign-up schedule for the project consultations between each of you and me, on Monday, February 18, from 1:30p - 3:15p. **Please submit a response on this issue thread of what consultation slot you want.** If you are working in a group of two, you will both meet with me at the same time.

I will also post on this page the different projects that each of you is doing.

Finally, I have posted LaTeX templates for writing a project document as well as a LaTeX beamer template for creating presentation slides.

@adamoppenheimer, @avasilj, @ccerda1, @dfnoriega, @keiirizawa, @originhal, @sergioservan, @tschwieg

**Comment by dfnoriega** [comment]
Starting 1:45

**Comment by originhal** [comment]
Starting 2:00

**Comment by originhal** [comment]
Starting 2:15 - Ginha Kim

**Comment by rickecon** [comment]
Got it, I have @dfnoriega at 1:45p and @originhal at 2:15p. I have updated the schedule with your info.

**Comment by keiirizawa** [comment]
Starting 2:30 - Kei Irizawa & Adam Oppenheimer

**Comment by rickecon** [comment]
Added @keiirizawa and @adamoppenheimer to the schedule at 2:30pm.

**Comment by ccerda1** [comment]
3:00 pm works for me.

**Comment by rickecon** [comment]
Added @ccerda1 to the schedule at 3pm.

**Comment by avasilj** [comment]
2:45 -  Ana

**Comment by tschwieg** [comment]
I'll do 1:30 - Timothy Schwieg
